
class RandomGenerator{

	constructor(min, max){
		//debugger;
		this.min = min;
		this.max = max;
		//takes in the minimum and maximum values
		//if they are not defined, it sets the minimum to 1, and the max to 10
		//makes storage for the random number
		if (this.min == undefined){
			this.min = 1;
		}
		if (this.max == undefined){
			this.max = 10;
		}
		this.randomNumber = null;
	}
	generate(){
		//make a random value between the minimum and maximum values
		//and store the number into the storage from the constructor
		this.randomNumber = Math.floor(this.min + Math.random()*(this.max + 1 - this.min));
	}
	getRange(){
		//return an object with min and max, min being the minimum value for the generator,
		// max being the maximum value
		//returns a basic object literal
		return {min:this.min, max:this.max};
	}
	getNum(){
		//return the random number that was generated by generate()
		return this.randomNumber;
	}
}

	// var x = new RandomGenerator(10, 50);
	// x.generate();
	// var randomNum = x.getNum();
	//
	// console.log ("x = ", x);
	// console.log ("range is ", x.getRange());
	// console.log ("random number is ", randomNum);
